# Generated by Django 6.0 on 2026-07-01 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Planta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_comun", models.CharField(max_length=150)),
                ("nombre_cientifico", models.CharField(max_length=200, unique=True)),
                ("familia_botanica", models.CharField(max_length=150)),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("NATIVA", "Nativa de Chile"),
                            ("ASILVESTRADA", "Asilvestrada de Uso Tradicional"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "zona_macro",
                    models.CharField(
                        choices=[
                            ("NORTE", "Norte"),
                            ("CENTRO", "Centro"),
                            ("SUR", "Sur"),
                            ("PATAGONIA", "Patagonia"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "regiones",
                    models.TextField(help_text="Lista de regiones separadas por comas"),
                ),
                ("habitat", models.TextField()),
                ("descripcion_hoja", models.TextField()),
                ("descripcion_tallo", models.TextField()),
                ("descripcion_flor", models.TextField()),
                (
                    "foto_real",
                    models.URLField(
                        help_text="URL de imagen real referencial o Pl@ntNet"
                    ),
                ),
                (
                    "uso_principal",
                    models.CharField(
                        help_text="Ej: Medicinal, Comestible, Venenosa", max_length=100
                    ),
                ),
                (
                    "efecto_terapeutico",
                    models.CharField(
                        help_text="Ej: Hepático, cicatrizante, ansiolítico",
                        max_length=150,
                    ),
                ),
                ("receta_preparacion", models.TextField()),
                ("advertencias", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Plantas",
            },
        ),
        migrations.CreateModel(
            name="Favorito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favoritos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "planta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favoritos",
                        to="plantas.planta",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Favoritos",
                "unique_together": {("usuario", "planta")},
            },
        ),
    ]
