# Generated by Django 6.0 on 2026-07-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planta",
            name="foto_real",
            field=models.ImageField(
                blank=True,
                help_text="Sube una imagen real referencial de la planta",
                null=True,
                upload_to="plantas/",
            ),
        ),
    ]
